IF COL_LENGTH('dbo.MONI_CABECERAMONITOREO', 'horas_frio_acumuladas') IS NULL
  ALTER TABLE dbo.MONI_CABECERAMONITOREO ADD horas_frio_acumuladas DECIMAL(10,2) NULL;

IF COL_LENGTH('dbo.MONI_CABECERAMONITOREO', 'dias_grado_acumulados') IS NULL
  ALTER TABLE dbo.MONI_CABECERAMONITOREO ADD dias_grado_acumulados DECIMAL(10,2) NULL;

IF COL_LENGTH('dbo.MONI_CABECERAMONITOREO', 'estacion_meteo_uuid') IS NULL
  ALTER TABLE dbo.MONI_CABECERAMONITOREO ADD estacion_meteo_uuid UNIQUEIDENTIFIER NULL;

IF COL_LENGTH('dbo.MONI_CABECERAMONITOREO', 'nombre_estacion_meteo') IS NULL
  ALTER TABLE dbo.MONI_CABECERAMONITOREO ADD nombre_estacion_meteo NVARCHAR(100) NULL;

IF COL_LENGTH('dbo.MONI_CABECERAMONITOREO', 'fecha_corte_agroclima') IS NULL
  ALTER TABLE dbo.MONI_CABECERAMONITOREO ADD fecha_corte_agroclima DATE NULL;

IF COL_LENGTH('dbo.MONI_CABECERAMONITOREO', 'semana_iso_corte') IS NULL
  ALTER TABLE dbo.MONI_CABECERAMONITOREO ADD semana_iso_corte TINYINT NULL;

IF COL_LENGTH('dbo.MONI_CABECERAMONITOREO', 'temporada_agroclima') IS NULL
  ALTER TABLE dbo.MONI_CABECERAMONITOREO ADD temporada_agroclima VARCHAR(9) NULL;

IF COL_LENGTH('dbo.MONI_CABECERAMONITOREO', 'agroclima_observacion') IS NULL
  ALTER TABLE dbo.MONI_CABECERAMONITOREO ADD agroclima_observacion NVARCHAR(250) NULL;
